
  - description: null
    label: "Globals"
    name: "clippings"
    sort: 1
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/clippings.yaml"
    fields:
      - name: "site_name"
        label: "Site Name"
        description: null
        datatype: "text"
        sort: 1
        required: true
        relationship: null
        settings:
          options: {}
      - name: "logo"
        label: "Site Logo"
        description: null
        datatype: "images"
        sort: 2
        required: null
        relationship: null
        settings:
          limit: 1
          options: {}
  - description: null
    label: "Homepage"
    name: "homepage"
    sort: 1
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/homepage.tpl"
    content: "/content/homepage.yaml"
    fields:
      - name: "test"
        label: "test"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "multi"
        label: "Multi"
        description: ""
        datatype: "one_to_many"
        sort: 4
        required: false
        relationship:
          name: "staff_role_type"
          display: "role"
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Stories"
    name: "stories"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/stories.tpl"
    content: "/content/stories.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "story_image"
        label: "Story Image"
        description: ""
        datatype: "images"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "start_date"
        label: "Start Date"
        description: ""
        datatype: "datetime"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "end_date"
        label: "End Date"
        description: ""
        datatype: "datetime"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "story_body"
        label: "Story Body"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 4
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "external_article"
        label: "External article"
        description: ""
        datatype: "yes_no"
        sort: 5
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
          options:
            0: "No"
            1: "Yes"
      - name: "press_release"
        label: "Press release"
        description: ""
        datatype: "yes_no"
        sort: 6
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
          options:
            0: "No"
            1: "Yes"
  - description: ""
    label: "Events"
    name: "events"
    sort: 101
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/events.tpl"
    content: "/content/events.yaml"
    fields:
      - name: "name"
        label: "Name"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "location"
        label: "Location"
        description: ""
        datatype: "textarea"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "event_image"
        label: "Event Image"
        description: ""
        datatype: "images"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "start_date"
        label: "Start Date"
        description: ""
        datatype: "datetime"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "end_date"
        label: "End Date"
        description: ""
        datatype: "datetime"
        sort: 4
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "cta_text_1"
        label: "CTA Text 1"
        description: ""
        datatype: "text"
        sort: 5
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "cta_url_1"
        label: "CTA URL 1"
        description: ""
        datatype: "link"
        sort: 6
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "cta_text_2"
        label: "CTA Text 2"
        description: ""
        datatype: "text"
        sort: 7
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "cta_url_2"
        label: "CTA URL 2"
        description: ""
        datatype: "text"
        sort: 8
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Staff"
    name: "staff"
    sort: 102
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/staff.yaml"
    fields:
      - name: "first_name"
        label: "First Name"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "middle_name"
        label: "Middle Name"
        description: ""
        datatype: "text"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "last_name"
        label: "Last Name"
        description: ""
        datatype: "text"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "profile"
        label: "Profile"
        description: ""
        datatype: "images"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "rank"
        label: "Rank"
        description: ""
        datatype: "text"
        sort: 4
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "job_role"
        label: "Job Role"
        description: ""
        datatype: "text"
        sort: 5
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "role_type"
        label: "Role Type"
        description: ""
        datatype: "one_to_one"
        sort: 6
        required: false
        relationship:
          name: "staff_role_type"
          display: "role"
        settings:
          defaultValue: null
          list: true
      - name: "email"
        label: "Email"
        description: ""
        datatype: "text"
        sort: 7
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "about"
        label: "About"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 8
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "test"
        label: "Test"
        description: ""
        datatype: "one_to_many"
        sort: 9
        required: false
        relationship:
          name: "staff_role_type"
          display: "role"
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Hours of operations"
    name: "hours_of_operations"
    sort: 106
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/hours_of_operations.yaml"
    fields: []
  - description: ""
    label: "Message of the day"
    name: "message_of_the_day"
    sort: 107
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/message_of_the_day.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "button_text"
        label: "Button Text"
        description: ""
        datatype: "text"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "button_link"
        label: "Button Link"
        description: ""
        datatype: "link"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 4
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "run_to_date"
        label: "Run to Date"
        description: ""
        datatype: "datetime"
        sort: 5
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "highlighted"
        label: "Highlighted"
        description: ""
        datatype: "yes_no"
        sort: 6
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
          options:
            0: "No"
            1: "Yes"
  - description: ""
    label: "Programs"
    name: "programs"
    sort: 108
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/programs.tpl"
    content: "/content/programs.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "service_image"
        label: "Service Image"
        description: ""
        datatype: "images"
        sort: 1
        required: false
        relationship: null
        settings:
          defaultValue: null
          limit: ""
          list: true
      - name: "start_date"
        label: "Start Date"
        description: ""
        datatype: "datetime"
        sort: 2
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
      - name: "service_body"
        label: "Service Body"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 3
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Program schedule"
    name: "program_schedule"
    sort: 109
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/program_schedule.yaml"
    fields: []
  - description: ""
    label: "Staff Role Type"
    name: "staff_role_type"
    sort: 110
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/staff_role_type.yaml"
    fields:
      - name: "role"
        label: "Role"
        description: ""
        datatype: "text"
        sort: 0
        required: false
        relationship: null
        settings:
          defaultValue: null
          list: true
  - description: ""
    label: "Homepage news"
    name: "homepage_news"
    sort: 155
    listed: true
    hasRoute: true
    showAsTable: true
    parent: null
    view: "/views/homepage_news.tpl"
    content: "/content/homepage_news.yaml"
    fields: []
